spring:
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
server:
    port: 8084

idm:
    servers:
        keystone: http://192.168.56.11:5000
        horizon: http://192.168.56.11:8000
    admin:
        username: idm
        password: idm

---
spring:
    profiles: development
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
server:
    port: 9000

idm:
    servers:
        keystone: http://192.168.56.11:5000
        horizon: http://192.168.56.11:8000
    admin:
        username: idm
        password: idm

---
spring:
    profiles: production
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
server:
    port: 8080

idm:
    servers:
        keystone: http://localhost:5000
        horizon: http://localhost:8000
    admin:
        username: idm
        password: idm
