spring:
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
    mail:
        active: true
        host: smtp.gmail.com
        port: 587
        protocol: smtp
        from: gitlab.infotec@gmail.com
        username: gitlab.infotec@gmail.com
        password: 
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    
server:
    port: 9000
    contextPath: /back-sdk

idm:
    servers:
        keystone: http://localhost:5000
        horizon: http://localhost:8000
        orion: http://localhost:1026
    admin:
        username: idm
        password: idm
    oauth:
        clientId: 
        clientSecret: 
    default:
        domain: default
front:
    url: http://localhost:4200/#

---
spring:
    profiles: development
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
    mail:
        active: false
        host: smtp.gmail.com
        port: 587
        protocol: smtp
        from: gitlab.infotec@gmail.com
        username: gitlab.infotec@gmail.com
        password: 
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
server:
    port: 9000
    contextPath: /back-sdk

idm:
    servers:
        keystone: http://localhost:5000
        horizon: http://localhost:8000
        orion: http://localhost:1026
    admin:
        username: idm
        password: idm
    oauth:
        clientId: 
        clientSecret: 
    default:
        domain: default
front:
    url: http://localhost:4200/#

---
spring:
    profiles: qa
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
    mail:
        active: true
        host: smtp.gmail.com
        port: 587
        protocol: smtp
        from: gitlab.infotec@gmail.com
        username: gitlab.infotec@gmail.com
        password: 
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
server:
    port: 8080
    contextPath: /back-sdk

# Rodrigo's cloud server
idm:
    servers:
        keystone: http://191.168.186.252:5000
        horizon: http://191.168.186.252:8000
        orion: http://192.168.56.11:1026
    admin:
        username: idm
        password: idm
    oauth:
        clientId: 
        clientSecret: 
front:
    url: http://207.249.127.180/#

---
spring:
    profiles: production
    application:
        name: back-sdk
    data:
        mongodb:
            database: smartcity
    mail:
        active: true
        host: smtp.gmail.com
        port: 587
        protocol: smtp
        from: gitlab.infotec@gmail.com
        username: gitlab.infotec@gmail.com
        password: 
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
server:
    port: 8080
    contextPath: /back-sdk

# Erik's cloud server
idm:
    servers:
        keystone: http://localhost:5000
        horizon: http://localhost:8000
        orion: http://localhost:1026
    admin:
        username: idm
        password: idm
    oauth:
        clientId:
        clientSecret:
    default:
        domain: default        
front:
    url: http://207.249.127.91/#
